package com.ct.fastreport.service.llm;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.util.concurrent.ThreadLocalRandom;

@Service
public class MockLLMService implements LLMService {

    @Value("${llm.mock.failure-rate:0.08}")
    private double failureRate;

    @Value("${llm.mock.min-latency-ms:20}")
    private long minLatencyMs;

    @Value("${llm.mock.max-latency-ms:80}")
    private long maxLatencyMs;

    @Override
    public String provider() {
        return "mock";
    }

    @Override
    public String generate(LLMGenerationRequest request) throws Exception {
        simulateLatency();

        if (ThreadLocalRandom.current().nextDouble() < failureRate) {
            throw new IllegalStateException("Mock LLM failure triggered for seeded traffic.");
        }

        String reportId = valueAfterPrefix(request.userPrompt(), "Report ID:");
        String customerName = valueAfterPrefix(request.userPrompt(), "Customer Name:");
        String serviceCode = valueAfterPrefix(request.userPrompt(), "Service Code:");
        String currentPlan = valueAfterPrefix(request.userPrompt(), "Current Plan:");
        String networkQuality = valueAfterPrefix(request.userPrompt(), "Network Quality:");

        return """
                # Report Summary
                ## Executive Summary
                - Report %s generated by the mock provider for seeded traffic.
                - Customer %s is currently on %s and should remain in the retention workflow.
                - Service health is acceptable overall with targeted follow-up recommended.

                ## Customer Profile
                - Customer: %s
                - Service Code: %s
                - Current Plan: %s

                ## Service Assessment
                - Recent usage and billing signals are consistent with an active broadband subscriber.
                - Service experience should be reviewed against complaint and network notes before upsell actions.
                - Mock provider output is intentionally concise but structured for realistic UI testing.

                ## Risk Signals
                - Network quality note: %s
                - Watch for repeat complaints, unstable speeds, and pricing sensitivity.

                ## Recommended Actions
                1. Confirm current service satisfaction with the account owner.
                2. Review complaint recovery status and open operational tasks.
                3. Propose a targeted retention or upgrade action only if quality stabilizes.

                ## Follow-Up Plan
                - Owner: Assigned account manager
                - Timeline: Within 3 business days
                - Success Measure: Customer keeps service and no new quality complaint is raised
                """.formatted(
                defaultValue(reportId, "N/A"),
                defaultValue(customerName, "Unknown Customer"),
                defaultValue(currentPlan, "Unknown Plan"),
                defaultValue(customerName, "Unknown Customer"),
                defaultValue(serviceCode, "Unknown Service"),
                defaultValue(currentPlan, "Unknown Plan"),
                defaultValue(networkQuality, "No network summary provided")
        ).strip();
    }

    private void simulateLatency() throws InterruptedException {
        long lower = Math.max(0L, minLatencyMs);
        long upper = Math.max(lower, maxLatencyMs);
        long sleepMs = upper == lower ? lower : ThreadLocalRandom.current().nextLong(lower, upper + 1L);
        if (sleepMs > 0L) {
            Thread.sleep(sleepMs);
        }
    }

    private String valueAfterPrefix(String text, String prefix) {
        for (String line : text.split("\\R")) {
            if (line.startsWith(prefix)) {
                return line.substring(prefix.length()).trim();
            }
        }
        return null;
    }

    private String defaultValue(String value, String fallback) {
        return value == null || value.isBlank() ? fallback : value;
    }
}
